# Generated by Django 6.1 on 2026-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0007_historicalmousebodyweight_water_restriction_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmousebodyweight',
            name='is_training_done',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
        migrations.AddField(
            model_name='mousebodyweight',
            name='is_training_done',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalmousebodyweight',
            name='water_restriction_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Water Restriction Start Date'),
        ),
        migrations.AlterField(
            model_name='mousebodyweight',
            name='water_restriction_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Water Restriction Start Date'),
        ),
    ]
