# Generated by Django 6.1 on 2026-09-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0008_historicalmousebodyweight_is_training_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmousebodyweight',
            name='is_training_done',
        ),
        migrations.RemoveField(
            model_name='mousebodyweight',
            name='is_training_done',
        ),
    ]
