# Generated by Django 6.1 on 2026-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0009_remove_historicalmousebodyweight_is_training_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyweightentry',
            name='is_training_done',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
        migrations.AddField(
            model_name='historicalbodyweightentry',
            name='is_training_done',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
    ]
