# Generated by Django 6.1 on 2026-09-24 10:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0027_remove_animal_owner_name_and_more'),
        ('training_metadata', '0010_bodyweightentry_is_training_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackchanges',
            name='category',
            field=models.CharField(choices=[('training_session', 'Training Session'), ('mouse_body_weight', 'Mouse Body Weight Record'), ('mouse_training', 'Mouse Training Record')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='animals_metadata.animal'),
        ),
        migrations.CreateModel(
            name='HistoricalMouseTrainingRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal', verbose_name='Animal ID')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mouse Training Record',
                'verbose_name_plural': 'historical Mouse Training Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MouseTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_record', to='animals_metadata.animal', verbose_name='Animal ID')),
            ],
            options={
                'verbose_name': 'Mouse Training Record',
                'verbose_name_plural': 'Mouse Training Records',
                'ordering': ['animal__animal_id'],
            },
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training_metadata.mousetrainingrecord', verbose_name='Mouse Training Record'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training_metadata.mousetrainingrecord', verbose_name='Mouse Training Record'),
        ),
    ]
