# Generated by Django 6.1 on 2026-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0011_alter_trackchanges_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyweightentry',
            options={'ordering': ['date'], 'verbose_name': 'Mouse Body Weight Entry', 'verbose_name_plural': 'Mouse Body Weight Entries'},
        ),
        migrations.AlterModelOptions(
            name='historicalbodyweightentry',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mouse Body Weight Entry', 'verbose_name_plural': 'historical Mouse Body Weight Entries'},
        ),
        migrations.AlterModelOptions(
            name='historicalmousebodyweight',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mouse Body Weight Record', 'verbose_name_plural': 'historical Mouse Body Weight Records'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrainingsession',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mouse Training Session', 'verbose_name_plural': 'historical Mouse Training Sessions'},
        ),
        migrations.AlterModelOptions(
            name='mousebodyweight',
            options={'ordering': ['animal__animal_id'], 'verbose_name': 'Mouse Body Weight Record', 'verbose_name_plural': 'Mouse Body Weight Records'},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-training_date'], 'verbose_name': 'Mouse Training Session', 'verbose_name_plural': 'Mouse Training Sessions'},
        ),
        migrations.AlterField(
            model_name='trackchanges',
            name='category',
            field=models.CharField(choices=[('training_session', 'Mouse Training Session'), ('mouse_body_weight', 'Mouse Body Weight Record'), ('mouse_training', 'Mouse Training Record')], max_length=30),
        ),
    ]
