# Generated by Django 6.1 on 2026-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0012_alter_bodyweightentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='include_in_mouse_tracker',
            field=models.BooleanField(default=True, help_text="Uncheck if this session should not be plotted on the mouse profile workstation d' graph (e.g. subset/troubleshooting runs).", verbose_name='include in mouse tracker?'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='include_in_mouse_tracker',
            field=models.BooleanField(default=True, help_text="Uncheck if this session should not be plotted on the mouse profile workstation d' graph (e.g. subset/troubleshooting runs).", verbose_name='include in mouse tracker?'),
        ),
    ]
