# Generated by Django 6.1 on 2026-09-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0013_historicaltrainingsession_include_in_mouse_tracker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmousebodyweight',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Body Weight Record', 'verbose_name_plural': 'historical Body Weight Records'},
        ),
        migrations.AlterModelOptions(
            name='historicalmousetrainingrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Training Record', 'verbose_name_plural': 'historical Training Records'},
        ),
        migrations.AlterModelOptions(
            name='mousebodyweight',
            options={'ordering': ['animal__animal_id'], 'verbose_name': 'Body Weight Record', 'verbose_name_plural': 'Body Weight Records'},
        ),
        migrations.AlterModelOptions(
            name='mousetrainingrecord',
            options={'ordering': ['animal__animal_id'], 'verbose_name': 'Training Record', 'verbose_name_plural': 'Training Records'},
        ),
        migrations.AlterField(
            model_name='bodyweightentry',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='training_metadata.mousebodyweight', verbose_name='Body Weight Record'),
        ),
        migrations.AlterField(
            model_name='historicalbodyweightentry',
            name='tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training_metadata.mousebodyweight', verbose_name='Body Weight Record'),
        ),
        migrations.AlterField(
            model_name='historicaltrainingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training_metadata.mousetrainingrecord', verbose_name='Training Record'),
        ),
        migrations.AlterField(
            model_name='trackchanges',
            name='category',
            field=models.CharField(choices=[('training_session', 'Mouse Training Session'), ('mouse_body_weight', 'Body Weight Record'), ('mouse_training', 'Training Record')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training_metadata.mousetrainingrecord', verbose_name='Training Record'),
        ),
    ]
