# Generated by Django 6.1 on 2026-09-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0014_alter_historicalmousebodyweight_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltrainingsession',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Training Session', 'verbose_name_plural': 'historical Training Sessions'},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-training_date'], 'verbose_name': 'Training Session', 'verbose_name_plural': 'Training Sessions'},
        ),
        migrations.AlterField(
            model_name='trackchanges',
            name='category',
            field=models.CharField(choices=[('training_session', 'Training Session'), ('mouse_body_weight', 'Body Weight Record'), ('mouse_training', 'Training Record')], max_length=30),
        ),
    ]
