# Generated by Django 6.1 on 2026-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0015_alter_historicaltrainingsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrainingsession',
            name='include_in_mouse_tracker',
            field=models.BooleanField(default=False, help_text="Check if this session should be plotted on the mouse profile workstation d' graph.", verbose_name='include in mouse tracker?'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='include_in_mouse_tracker',
            field=models.BooleanField(default=False, help_text="Check if this session should be plotted on the mouse profile workstation d' graph.", verbose_name='include in mouse tracker?'),
        ),
    ]
