"""
Django settings for PStim_DAP project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-development-pstim-pipeline-secret-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

_allowed_hosts_raw = os.getenv("DJANGO_ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(",") if h.strip()] if _allowed_hosts_raw else []


# =============================================================================
# Deployment Profile & Application Definition
# =============================================================================

DJANGO_BASE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simple_history',
]

DEPLOYMENT_PROFILES = {
    'CORE': [
        'animals_metadata',
        'virus_metadata',
    ],
    'IMAGING': [
        'animals_metadata',
        'virus_metadata',
        'imaging_metadata',
    ],
    'IMAGING_ANALYSIS': [
        'animals_metadata',
        'virus_metadata',
        'imaging_metadata',
        'imaging_analysis_metadata',
    ],
    'TRAINING': [
        'animals_metadata',
        'virus_metadata',
        'training_metadata',
    ],
    'FULL': [
        'animals_metadata',
        'virus_metadata',
        'imaging_metadata',
        'imaging_analysis_metadata',
        'training_metadata',
    ],
}

PSTIM_PROFILE = os.getenv("PSTIM_PROFILE", "FULL").strip().upper().replace(" ", "_")

if PSTIM_PROFILE not in DEPLOYMENT_PROFILES:
    valid_profiles = ", ".join(DEPLOYMENT_PROFILES.keys())
    raise ImproperlyConfigured(
        f"Invalid PSTIM_PROFILE '{PSTIM_PROFILE}'. "
        f"Supported deployment profiles are: {valid_profiles}."
    )

INSTALLED_APPS = DJANGO_BASE_APPS + DEPLOYMENT_PROFILES[PSTIM_PROFILE]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'PStim_DAP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'PStim_DAP.context_processors.enabled_apps',
            ],
        },
    },
]

WSGI_APPLICATION = 'PStim_DAP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# =============================================================================
# Two-Photon Analysis & Suite2P Pipeline Configuration
# =============================================================================

SUITE2P_PYTHON_PATH = os.environ.get(
    "SUITE2P_PYTHON_PATH",
    r"C:\Users\abhrajyoti.chakrabarti\Documents\suite2p_venv\suite2p\.venv\Scripts\python.exe",
)

SUITE2P_RUNNER_SCRIPT = os.environ.get(
    "SUITE2P_RUNNER_SCRIPT",
    r"C:\Users\abhrajyoti.chakrabarti\Documents\suite2p_venv\suite2p\customScripts\analysis_runner.py",
)

# Push Notification Settings
NTFY_ENABLED = True
NTFY_TOPIC = "StimBEAM_AJ"
NTFY_SERVER = "http://127.0.0.1:8080"
NTFY_AUTH_TOKEN = os.environ.get("NTFY_AUTH_TOKEN")