# Generated by Django 6.1 on 2026-09-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_metadata', '0006_trackchanges_historicalimagingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimagingsession',
            name='analysis_performed',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
        migrations.AddField(
            model_name='historicalimagingsession',
            name='need_for_analysis',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
        migrations.AddField(
            model_name='imagingsession',
            name='analysis_performed',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
        migrations.AddField(
            model_name='imagingsession',
            name='need_for_analysis',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True),
        ),
    ]
