# Generated by Django 6.1 on 2026-09-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_metadata', '0007_historicalimagingsession_analysis_performed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimagingsession',
            name='analysis_performed',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True, verbose_name='Analysis Performed?'),
        ),
        migrations.AlterField(
            model_name='historicalimagingsession',
            name='need_for_analysis',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True, verbose_name='Required for Analysis?'),
        ),
        migrations.AlterField(
            model_name='imagingsession',
            name='analysis_performed',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True, verbose_name='Analysis Performed?'),
        ),
        migrations.AlterField(
            model_name='imagingsession',
            name='need_for_analysis',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], null=True, verbose_name='Required for Analysis?'),
        ),
    ]
