# Generated by Django 6.1 on 2026-09-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_metadata', '0008_alter_historicalimagingsession_analysis_performed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimagingsession',
            name='analysis_performed',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('D', 'Record Deleted')], null=True, verbose_name='Analysis Performed?'),
        ),
        migrations.AlterField(
            model_name='imagingsession',
            name='analysis_performed',
            field=models.TextField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('D', 'Record Deleted')], null=True, verbose_name='Analysis Performed?'),
        ),
    ]
