# Generated by Django 6.1 on 2026-09-25 08:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def populate_imaging_records(apps, schema_editor):
    Animal = apps.get_model('animals_metadata', 'Animal')
    MouseImagingRecord = apps.get_model('imaging_metadata', 'MouseImagingRecord')
    ImagingSession = apps.get_model('imaging_metadata', 'ImagingSession')

    for animal in Animal.objects.all():
        MouseImagingRecord.objects.get_or_create(animal=animal)

    for session in ImagingSession.objects.all():
        if session.animal_id and not session.tracker_id:
            tracker, _ = MouseImagingRecord.objects.get_or_create(animal_id=session.animal_id)
            session.tracker = tracker
            session.save(update_fields=['tracker'])


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0027_remove_animal_owner_name_and_more'),
        ('imaging_metadata', '0009_alter_historicalimagingsession_analysis_performed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingsession',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_sessions', to='animals_metadata.animal'),
        ),
        migrations.AlterField(
            model_name='trackchanges',
            name='category',
            field=models.CharField(choices=[('imaging_session', 'Imaging Session'), ('mouse_imaging', 'Mouse Imaging Record')], max_length=30),
        ),
        migrations.CreateModel(
            name='HistoricalMouseImagingRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal', verbose_name='Animal ID')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mouse Imaging Record',
                'verbose_name_plural': 'historical Mouse Imaging Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MouseImagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_record', to='animals_metadata.animal', verbose_name='Animal ID')),
            ],
            options={
                'verbose_name': 'Mouse Imaging Record',
                'verbose_name_plural': 'Mouse Imaging Records',
                'ordering': ['animal__animal_id'],
            },
        ),
        migrations.AddField(
            model_name='historicalimagingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='imaging_metadata.mouseimagingrecord', verbose_name='Mouse Imaging Record'),
        ),
        migrations.AddField(
            model_name='imagingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='imaging_metadata.mouseimagingrecord', verbose_name='Mouse Imaging Record'),
        ),
        migrations.RunPython(
            code=populate_imaging_records,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
