# Generated by Django 6.1 on 2026-09-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_metadata', '0010_alter_imagingsession_animal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmouseimagingrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Imaging Record', 'verbose_name_plural': 'historical Imaging Records'},
        ),
        migrations.AlterModelOptions(
            name='mouseimagingrecord',
            options={'ordering': ['animal__animal_id'], 'verbose_name': 'Imaging Record', 'verbose_name_plural': 'Imaging Records'},
        ),
        migrations.AlterField(
            model_name='historicalimagingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='imaging_metadata.mouseimagingrecord', verbose_name='Imaging Record'),
        ),
        migrations.AlterField(
            model_name='imagingsession',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='imaging_metadata.mouseimagingrecord', verbose_name='Imaging Record'),
        ),
        migrations.AlterField(
            model_name='trackchanges',
            name='category',
            field=models.CharField(choices=[('imaging_session', 'Imaging Session'), ('mouse_imaging', 'Imaging Record')], max_length=30),
        ),
    ]
