# Generated by Django 6.1 on 2026-09-11 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_metadata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE virus_metadata_virus SET virus_owner = NULL;
            UPDATE virus_metadata_historicalvirus SET virus_owner = NULL;
            """,
            reverse_sql="",
        ),
        migrations.AlterField(
            model_name='historicalvirus',
            name='virus_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Virus Owner'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='virus_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Virus Owner'),
        ),
    ]
