# Generated by Django 6.1 on 2026-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0022_alter_historicalvisioncheck_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pipeline_stage',
            field=models.CharField(blank=True, choices=[('Intake', 'Intake'), ('Vision Check', 'Vision Check'), ('Virus Injection', 'Virus Injection'), ('Surgery', 'Surgery'), ('Behavior Training', 'Behavior Training'), ('Finished', 'Finished'), ('Culled', 'Culled')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalanimal',
            name='pipeline_stage',
            field=models.CharField(blank=True, choices=[('Intake', 'Intake'), ('Vision Check', 'Vision Check'), ('Virus Injection', 'Virus Injection'), ('Surgery', 'Surgery'), ('Behavior Training', 'Behavior Training'), ('Finished', 'Finished'), ('Culled', 'Culled')], max_length=100, null=True),
        ),
    ]
