# Generated by Django 6.1 on 2026-09-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0024_animal_owner_2_historicalanimal_owner_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='owner_2',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='historicalanimal',
            old_name='owner_2',
            new_name='owner_name',
        ),
    ]
