# Generated by Django 6.1 on 2026-09-11 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0026_alter_animal_owner_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE animals_metadata_animal SET owner = NULL;
            UPDATE animals_metadata_historicalanimal SET owner = NULL;
            UPDATE animals_metadata_viralinjection SET injecting_person = NULL, surgery_person = NULL;
            UPDATE animals_metadata_historicalviralinjection SET injecting_person = NULL, surgery_person = NULL;
            """,
            reverse_sql="",
        ),
        migrations.RemoveField(
            model_name='animal',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='historicalanimal',
            name='owner_name',
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='historicalanimal',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='injecting_person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Inj. Person'),
        ),
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='surgery_person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Surgery Done By'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='injecting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injections_performed', to=settings.AUTH_USER_MODEL, verbose_name='Inj. Person'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='surgery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_performed', to=settings.AUTH_USER_MODEL, verbose_name='Surgery Done By'),
        ),
    ]
